# SwiftLint Configuration for Wallpier
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - wallpier

# Paths to exclude from linting
excluded:
  - wallpierTests
  - wallpierUITests
  - wallpier.xcodeproj
  - DerivedData
  - .build

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length # Handled by custom rule below
  - todo # Allow TODO comments during development

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rule configurations
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 70
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - ok
    - to
    - vm

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 70

large_tuple:
  warning: 3
  error: 4

# Force unwrap/cast configuration
force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

# Import ordering
sorted_imports:
  severity: warning

# Trailing comma preference
trailing_comma:
  mandatory_comma: false

# Colon style
colon:
  apply_to_dictionaries: true

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# File header template
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  wallpier
    \/\/

# Custom rules
custom_rules:
  # Encourage using async/await over completion handlers
  prefer_async_await:
    name: "Prefer async/await"
    regex: "completionHandler|completion:|@escaping.*->\\s*Void\\)"
    message: "Consider using async/await instead of completion handlers where possible."
    severity: warning

  # Avoid print statements in production code
  no_print_statement:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use Logger instead of print() for production code."
    severity: warning
    match_kinds:
      - identifier

  # Mark all service protocols with @MainActor
  service_protocol_main_actor:
    name: "Service Protocol MainActor"
    regex: "protocol\\s+\\w+ServiceProtocol(?!.*@MainActor)"
    message: "Service protocols should be marked with @MainActor for thread safety."
    severity: warning

# Reporter type
reporter: "xcode"
